[workspace]
members = [
    "crates/diarize-rs",
    "crates/nemotron-rs",
    "crates/sona",
    "crates/vad-rs",
    "crates/xtask",
    "crates/whisper-cpp-sys",
    "crates/whisper-rs",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/thewh1teagle/sona"
