name: Bug Report
description: File a bug report
labels: ["bug"]
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
              One second before you create, search if it's already reported [issues](https://github.com/thewh1teagle/vibe/issues?q=is:issue+label:bug+)

              Please, if possible, just open settings in vibe, and click 'Report Bug'
              This way I'll get all the relevant info required

              If not reported, if possible please check [Debug.md](https://github.com/thewh1teagle/vibe/blob/main/docs/debug.md) and add comments with more info.

    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: What you did, what happened instead, and what you expected.
      validations:
          required: true
    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps to reproduce
          description: The shortest path from a fresh start to the bug.
          placeholder: |
              1. Open Vibe and pick a model
              2. Drop in a 3 minute mp3
              3. Transcription stops at 40%
      validations:
          required: true
    - type: dropdown
      id: browsers
      attributes:
          label: What OS are you seeing the problem on?
          multiple: true
          options:
              - Window
              - Linux
              - MacOS
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: |
              Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.

          render: shell
