import type { SourceConfig } from "@/types";

export const SOURCES: SourceConfig[] = [
  // --- Live sources: fetched directly from official site on each page load ---
  {
    id: "uk",
    nameNl: "Verenigd Koninkrijk",
    nameEn: "United Kingdom",
    countryIso2: "GB",
    flagEmoji: "🇬🇧",
    baseUrl: "https://www.gov.uk/foreign-travel-advice",
    fetchMethod: "json_api",
    active: true,
    fetchIntervalH: 6,
    priority: 1,
    liveMode: true,
  },
  {
    id: "us",
    nameNl: "Verenigde Staten",
    nameEn: "United States",
    countryIso2: "US",
    flagEmoji: "🇺🇸",
    baseUrl: "https://travel.state.gov",
    fetchMethod: "json_api",
    active: true,
    fetchIntervalH: 6,
    priority: 1,
    liveMode: true,
  },
  {
    id: "germany",
    nameNl: "Duitsland",
    nameEn: "Germany",
    countryIso2: "DE",
    flagEmoji: "🇩🇪",
    baseUrl: "https://www.auswaertiges-amt.de",
    fetchMethod: "html",
    active: true,
    fetchIntervalH: 6,
    priority: 1,
    liveMode: false,
  },
  {
    id: "france",
    nameNl: "Frankrijk",
    nameEn: "France",
    countryIso2: "FR",
    flagEmoji: "🇫🇷",
    baseUrl: "https://www.diplomatie.gouv.fr",
    fetchMethod: "html",
    active: true,
    fetchIntervalH: 6,
    priority: 1,
    liveMode: true,
  },
  {
    id: "canada",
    nameNl: "Canada",
    nameEn: "Canada",
    countryIso2: "CA",
    flagEmoji: "🇨🇦",
    baseUrl: "https://travel.gc.ca",
    fetchMethod: "xml_feed",
    active: true,
    fetchIntervalH: 6,
    priority: 1,
    liveMode: false,
  },
  // --- Cached sources: official sites blocked from cloud; refreshed via daily scrape ---
  {
    id: "australia",
    nameNl: "Australië",
    nameEn: "Australia",
    countryIso2: "AU",
    flagEmoji: "🇦🇺",
    baseUrl: "https://www.smartraveller.gov.au",
    fetchMethod: "json_api",
    active: true,
    fetchIntervalH: 6,
    priority: 1,
    liveMode: false,
  },
  {
    id: "denmark",
    nameNl: "Denemarken",
    nameEn: "Denmark",
    countryIso2: "DK",
    flagEmoji: "🇩🇰",
    baseUrl: "https://um.dk",
    fetchMethod: "html",
    active: true,
    fetchIntervalH: 6,
    priority: 1,
    liveMode: false,
  },
  {
    id: "sweden",
    nameNl: "Zweden",
    nameEn: "Sweden",
    countryIso2: "SE",
    flagEmoji: "🇸🇪",
    baseUrl: "https://www.ud.se",
    fetchMethod: "html",
    active: true,
    fetchIntervalH: 6,
    priority: 1,
    liveMode: false,
  },
];

export const SOURCE_MAP = Object.fromEntries(SOURCES.map((s) => [s.id, s]));
