import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { SOURCES } from "../src/config/sources";

const adapter = new PrismaBetterSqlite3({ url: "file:./dev.db" });
const prisma = new PrismaClient({ adapter } as never);

const COUNTRIES = [
  // Europa
  { isoAlpha2: "AL", isoAlpha3: "ALB", nameNl: "Albanië", nameEn: "Albania", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "AD", isoAlpha3: "AND", nameNl: "Andorra", nameEn: "Andorra", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "AT", isoAlpha3: "AUT", nameNl: "Oostenrijk", nameEn: "Austria", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "BY", isoAlpha3: "BLR", nameNl: "Belarus", nameEn: "Belarus", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "BE", isoAlpha3: "BEL", nameNl: "België", nameEn: "Belgium", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "BA", isoAlpha3: "BIH", nameNl: "Bosnië-Herzegovina", nameEn: "Bosnia and Herzegovina", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "BG", isoAlpha3: "BGR", nameNl: "Bulgarije", nameEn: "Bulgaria", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "HR", isoAlpha3: "HRV", nameNl: "Kroatië", nameEn: "Croatia", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "CY", isoAlpha3: "CYP", nameNl: "Cyprus", nameEn: "Cyprus", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "CZ", isoAlpha3: "CZE", nameNl: "Tsjechië", nameEn: "Czech Republic", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "DK", isoAlpha3: "DNK", nameNl: "Denemarken", nameEn: "Denmark", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "EE", isoAlpha3: "EST", nameNl: "Estland", nameEn: "Estonia", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "FI", isoAlpha3: "FIN", nameNl: "Finland", nameEn: "Finland", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "FR", isoAlpha3: "FRA", nameNl: "Frankrijk", nameEn: "France", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "DE", isoAlpha3: "DEU", nameNl: "Duitsland", nameEn: "Germany", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "GR", isoAlpha3: "GRC", nameNl: "Griekenland", nameEn: "Greece", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "HU", isoAlpha3: "HUN", nameNl: "Hongarije", nameEn: "Hungary", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "IS", isoAlpha3: "ISL", nameNl: "IJsland", nameEn: "Iceland", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "IE", isoAlpha3: "IRL", nameNl: "Ierland", nameEn: "Ireland", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "IT", isoAlpha3: "ITA", nameNl: "Italië", nameEn: "Italy", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "XK", isoAlpha3: "XKX", nameNl: "Kosovo", nameEn: "Kosovo", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "LV", isoAlpha3: "LVA", nameNl: "Letland", nameEn: "Latvia", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "LI", isoAlpha3: "LIE", nameNl: "Liechtenstein", nameEn: "Liechtenstein", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "LT", isoAlpha3: "LTU", nameNl: "Litouwen", nameEn: "Lithuania", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "LU", isoAlpha3: "LUX", nameNl: "Luxemburg", nameEn: "Luxembourg", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "MT", isoAlpha3: "MLT", nameNl: "Malta", nameEn: "Malta", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "MD", isoAlpha3: "MDA", nameNl: "Moldavië", nameEn: "Moldova", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "MC", isoAlpha3: "MCO", nameNl: "Monaco", nameEn: "Monaco", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "ME", isoAlpha3: "MNE", nameNl: "Montenegro", nameEn: "Montenegro", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "NL", isoAlpha3: "NLD", nameNl: "Nederland", nameEn: "Netherlands", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "MK", isoAlpha3: "MKD", nameNl: "Noord-Macedonië", nameEn: "North Macedonia", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "NO", isoAlpha3: "NOR", nameNl: "Noorwegen", nameEn: "Norway", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "PL", isoAlpha3: "POL", nameNl: "Polen", nameEn: "Poland", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "PT", isoAlpha3: "PRT", nameNl: "Portugal", nameEn: "Portugal", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "RO", isoAlpha3: "ROU", nameNl: "Roemenië", nameEn: "Romania", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "RU", isoAlpha3: "RUS", nameNl: "Rusland", nameEn: "Russia", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "SM", isoAlpha3: "SMR", nameNl: "San Marino", nameEn: "San Marino", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "RS", isoAlpha3: "SRB", nameNl: "Servië", nameEn: "Serbia", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "SK", isoAlpha3: "SVK", nameNl: "Slowakije", nameEn: "Slovakia", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "SI", isoAlpha3: "SVN", nameNl: "Slovenië", nameEn: "Slovenia", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "ES", isoAlpha3: "ESP", nameNl: "Spanje", nameEn: "Spain", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "SE", isoAlpha3: "SWE", nameNl: "Zweden", nameEn: "Sweden", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "CH", isoAlpha3: "CHE", nameNl: "Zwitserland", nameEn: "Switzerland", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "TR", isoAlpha3: "TUR", nameNl: "Turkije", nameEn: "Turkey", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "UA", isoAlpha3: "UKR", nameNl: "Oekraïne", nameEn: "Ukraine", regionNl: "Europa", regionEn: "Europe" },
  { isoAlpha2: "GB", isoAlpha3: "GBR", nameNl: "Verenigd Koninkrijk", nameEn: "United Kingdom", regionNl: "Europa", regionEn: "Europe" },
  // Midden-Oosten
  { isoAlpha2: "BH", isoAlpha3: "BHR", nameNl: "Bahrein", nameEn: "Bahrain", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "IR", isoAlpha3: "IRN", nameNl: "Iran", nameEn: "Iran", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "IQ", isoAlpha3: "IRQ", nameNl: "Irak", nameEn: "Iraq", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "IL", isoAlpha3: "ISR", nameNl: "Israël", nameEn: "Israel", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "JO", isoAlpha3: "JOR", nameNl: "Jordanië", nameEn: "Jordan", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "KW", isoAlpha3: "KWT", nameNl: "Koeweit", nameEn: "Kuwait", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "LB", isoAlpha3: "LBN", nameNl: "Libanon", nameEn: "Lebanon", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "OM", isoAlpha3: "OMN", nameNl: "Oman", nameEn: "Oman", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "PS", isoAlpha3: "PSE", nameNl: "Palestina", nameEn: "Palestine", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "QA", isoAlpha3: "QAT", nameNl: "Qatar", nameEn: "Qatar", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "SA", isoAlpha3: "SAU", nameNl: "Saudi-Arabië", nameEn: "Saudi Arabia", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "SY", isoAlpha3: "SYR", nameNl: "Syrië", nameEn: "Syria", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "AE", isoAlpha3: "ARE", nameNl: "Verenigde Arabische Emiraten", nameEn: "United Arab Emirates", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  { isoAlpha2: "YE", isoAlpha3: "YEM", nameNl: "Jemen", nameEn: "Yemen", regionNl: "Midden-Oosten", regionEn: "Middle East" },
  // Afrika
  { isoAlpha2: "DZ", isoAlpha3: "DZA", nameNl: "Algerije", nameEn: "Algeria", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "AO", isoAlpha3: "AGO", nameNl: "Angola", nameEn: "Angola", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "BJ", isoAlpha3: "BEN", nameNl: "Benin", nameEn: "Benin", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "BW", isoAlpha3: "BWA", nameNl: "Botswana", nameEn: "Botswana", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "BF", isoAlpha3: "BFA", nameNl: "Burkina Faso", nameEn: "Burkina Faso", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "BI", isoAlpha3: "BDI", nameNl: "Burundi", nameEn: "Burundi", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "CV", isoAlpha3: "CPV", nameNl: "Kaapverdië", nameEn: "Cape Verde", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "CM", isoAlpha3: "CMR", nameNl: "Kameroen", nameEn: "Cameroon", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "CF", isoAlpha3: "CAF", nameNl: "Centraal-Afrikaanse Republiek", nameEn: "Central African Republic", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "TD", isoAlpha3: "TCD", nameNl: "Tsjaad", nameEn: "Chad", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "CD", isoAlpha3: "COD", nameNl: "Congo (DRC)", nameEn: "Congo (DRC)", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "CG", isoAlpha3: "COG", nameNl: "Congo (Republiek)", nameEn: "Congo (Republic)", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "CI", isoAlpha3: "CIV", nameNl: "Ivoorkust", nameEn: "Ivory Coast", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "DJ", isoAlpha3: "DJI", nameNl: "Djibouti", nameEn: "Djibouti", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "EG", isoAlpha3: "EGY", nameNl: "Egypte", nameEn: "Egypt", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "ER", isoAlpha3: "ERI", nameNl: "Eritrea", nameEn: "Eritrea", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "ET", isoAlpha3: "ETH", nameNl: "Ethiopië", nameEn: "Ethiopia", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "GA", isoAlpha3: "GAB", nameNl: "Gabon", nameEn: "Gabon", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "GM", isoAlpha3: "GMB", nameNl: "Gambia", nameEn: "Gambia", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "GH", isoAlpha3: "GHA", nameNl: "Ghana", nameEn: "Ghana", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "GN", isoAlpha3: "GIN", nameNl: "Guinee", nameEn: "Guinea", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "GW", isoAlpha3: "GNB", nameNl: "Guinee-Bissau", nameEn: "Guinea-Bissau", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "KE", isoAlpha3: "KEN", nameNl: "Kenia", nameEn: "Kenya", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "LS", isoAlpha3: "LSO", nameNl: "Lesotho", nameEn: "Lesotho", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "LR", isoAlpha3: "LBR", nameNl: "Liberia", nameEn: "Liberia", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "LY", isoAlpha3: "LBY", nameNl: "Libië", nameEn: "Libya", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "MG", isoAlpha3: "MDG", nameNl: "Madagaskar", nameEn: "Madagascar", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "MW", isoAlpha3: "MWI", nameNl: "Malawi", nameEn: "Malawi", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "ML", isoAlpha3: "MLI", nameNl: "Mali", nameEn: "Mali", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "MR", isoAlpha3: "MRT", nameNl: "Mauritanië", nameEn: "Mauritania", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "MU", isoAlpha3: "MUS", nameNl: "Mauritius", nameEn: "Mauritius", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "MA", isoAlpha3: "MAR", nameNl: "Marokko", nameEn: "Morocco", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "MZ", isoAlpha3: "MOZ", nameNl: "Mozambique", nameEn: "Mozambique", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "NA", isoAlpha3: "NAM", nameNl: "Namibië", nameEn: "Namibia", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "NE", isoAlpha3: "NER", nameNl: "Niger", nameEn: "Niger", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "NG", isoAlpha3: "NGA", nameNl: "Nigeria", nameEn: "Nigeria", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "RW", isoAlpha3: "RWA", nameNl: "Rwanda", nameEn: "Rwanda", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "ST", isoAlpha3: "STP", nameNl: "Sao Tomé en Principe", nameEn: "Sao Tome and Principe", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "SN", isoAlpha3: "SEN", nameNl: "Senegal", nameEn: "Senegal", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "SC", isoAlpha3: "SYC", nameNl: "Seychellen", nameEn: "Seychelles", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "SL", isoAlpha3: "SLE", nameNl: "Sierra Leone", nameEn: "Sierra Leone", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "SO", isoAlpha3: "SOM", nameNl: "Somalië", nameEn: "Somalia", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "ZA", isoAlpha3: "ZAF", nameNl: "Zuid-Afrika", nameEn: "South Africa", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "SS", isoAlpha3: "SSD", nameNl: "Zuid-Sudan", nameEn: "South Sudan", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "SD", isoAlpha3: "SDN", nameNl: "Sudan", nameEn: "Sudan", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "SZ", isoAlpha3: "SWZ", nameNl: "Eswatini", nameEn: "Eswatini", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "TZ", isoAlpha3: "TZA", nameNl: "Tanzania", nameEn: "Tanzania", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "TG", isoAlpha3: "TGO", nameNl: "Togo", nameEn: "Togo", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "TN", isoAlpha3: "TUN", nameNl: "Tunesië", nameEn: "Tunisia", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "UG", isoAlpha3: "UGA", nameNl: "Oeganda", nameEn: "Uganda", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "ZM", isoAlpha3: "ZMB", nameNl: "Zambia", nameEn: "Zambia", regionNl: "Afrika", regionEn: "Africa" },
  { isoAlpha2: "ZW", isoAlpha3: "ZWE", nameNl: "Zimbabwe", nameEn: "Zimbabwe", regionNl: "Afrika", regionEn: "Africa" },
  // Azië
  { isoAlpha2: "AF", isoAlpha3: "AFG", nameNl: "Afghanistan", nameEn: "Afghanistan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "AM", isoAlpha3: "ARM", nameNl: "Armenië", nameEn: "Armenia", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "AZ", isoAlpha3: "AZE", nameNl: "Azerbeidzjan", nameEn: "Azerbaijan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "BD", isoAlpha3: "BGD", nameNl: "Bangladesh", nameEn: "Bangladesh", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "BT", isoAlpha3: "BTN", nameNl: "Bhutan", nameEn: "Bhutan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "BN", isoAlpha3: "BRN", nameNl: "Brunei", nameEn: "Brunei", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "KH", isoAlpha3: "KHM", nameNl: "Cambodja", nameEn: "Cambodia", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "CN", isoAlpha3: "CHN", nameNl: "China", nameEn: "China", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "GE", isoAlpha3: "GEO", nameNl: "Georgië", nameEn: "Georgia", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "IN", isoAlpha3: "IND", nameNl: "India", nameEn: "India", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "ID", isoAlpha3: "IDN", nameNl: "Indonesië", nameEn: "Indonesia", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "JP", isoAlpha3: "JPN", nameNl: "Japan", nameEn: "Japan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "KZ", isoAlpha3: "KAZ", nameNl: "Kazachstan", nameEn: "Kazakhstan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "KP", isoAlpha3: "PRK", nameNl: "Noord-Korea", nameEn: "North Korea", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "KR", isoAlpha3: "KOR", nameNl: "Zuid-Korea", nameEn: "South Korea", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "KG", isoAlpha3: "KGZ", nameNl: "Kirgizstan", nameEn: "Kyrgyzstan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "LA", isoAlpha3: "LAO", nameNl: "Laos", nameEn: "Laos", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "MY", isoAlpha3: "MYS", nameNl: "Maleisië", nameEn: "Malaysia", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "MV", isoAlpha3: "MDV", nameNl: "Malediven", nameEn: "Maldives", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "MN", isoAlpha3: "MNG", nameNl: "Mongolië", nameEn: "Mongolia", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "MM", isoAlpha3: "MMR", nameNl: "Myanmar", nameEn: "Myanmar", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "NP", isoAlpha3: "NPL", nameNl: "Nepal", nameEn: "Nepal", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "PK", isoAlpha3: "PAK", nameNl: "Pakistan", nameEn: "Pakistan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "PH", isoAlpha3: "PHL", nameNl: "Filipijnen", nameEn: "Philippines", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "SG", isoAlpha3: "SGP", nameNl: "Singapore", nameEn: "Singapore", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "LK", isoAlpha3: "LKA", nameNl: "Sri Lanka", nameEn: "Sri Lanka", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "TW", isoAlpha3: "TWN", nameNl: "Taiwan", nameEn: "Taiwan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "TJ", isoAlpha3: "TJK", nameNl: "Tadzjikistan", nameEn: "Tajikistan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "TH", isoAlpha3: "THA", nameNl: "Thailand", nameEn: "Thailand", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "TL", isoAlpha3: "TLS", nameNl: "Oost-Timor", nameEn: "Timor-Leste", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "TM", isoAlpha3: "TKM", nameNl: "Turkmenistan", nameEn: "Turkmenistan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "UZ", isoAlpha3: "UZB", nameNl: "Oezbekistan", nameEn: "Uzbekistan", regionNl: "Azië", regionEn: "Asia" },
  { isoAlpha2: "VN", isoAlpha3: "VNM", nameNl: "Vietnam", nameEn: "Vietnam", regionNl: "Azië", regionEn: "Asia" },
  // Amerika
  { isoAlpha2: "AG", isoAlpha3: "ATG", nameNl: "Antigua en Barbuda", nameEn: "Antigua and Barbuda", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "AR", isoAlpha3: "ARG", nameNl: "Argentinië", nameEn: "Argentina", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "BS", isoAlpha3: "BHS", nameNl: "Bahama's", nameEn: "Bahamas", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "BB", isoAlpha3: "BRB", nameNl: "Barbados", nameEn: "Barbados", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "BZ", isoAlpha3: "BLZ", nameNl: "Belize", nameEn: "Belize", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "BO", isoAlpha3: "BOL", nameNl: "Bolivia", nameEn: "Bolivia", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "BR", isoAlpha3: "BRA", nameNl: "Brazilië", nameEn: "Brazil", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "CA", isoAlpha3: "CAN", nameNl: "Canada", nameEn: "Canada", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "CL", isoAlpha3: "CHL", nameNl: "Chili", nameEn: "Chile", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "CO", isoAlpha3: "COL", nameNl: "Colombia", nameEn: "Colombia", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "CR", isoAlpha3: "CRI", nameNl: "Costa Rica", nameEn: "Costa Rica", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "CU", isoAlpha3: "CUB", nameNl: "Cuba", nameEn: "Cuba", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "DM", isoAlpha3: "DMA", nameNl: "Dominica", nameEn: "Dominica", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "DO", isoAlpha3: "DOM", nameNl: "Dominicaanse Republiek", nameEn: "Dominican Republic", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "EC", isoAlpha3: "ECU", nameNl: "Ecuador", nameEn: "Ecuador", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "SV", isoAlpha3: "SLV", nameNl: "El Salvador", nameEn: "El Salvador", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "GD", isoAlpha3: "GRD", nameNl: "Grenada", nameEn: "Grenada", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "GT", isoAlpha3: "GTM", nameNl: "Guatemala", nameEn: "Guatemala", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "GY", isoAlpha3: "GUY", nameNl: "Guyana", nameEn: "Guyana", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "HT", isoAlpha3: "HTI", nameNl: "Haïti", nameEn: "Haiti", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "HN", isoAlpha3: "HND", nameNl: "Honduras", nameEn: "Honduras", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "JM", isoAlpha3: "JAM", nameNl: "Jamaica", nameEn: "Jamaica", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "MX", isoAlpha3: "MEX", nameNl: "Mexico", nameEn: "Mexico", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "NI", isoAlpha3: "NIC", nameNl: "Nicaragua", nameEn: "Nicaragua", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "PA", isoAlpha3: "PAN", nameNl: "Panama", nameEn: "Panama", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "PY", isoAlpha3: "PRY", nameNl: "Paraguay", nameEn: "Paraguay", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "PE", isoAlpha3: "PER", nameNl: "Peru", nameEn: "Peru", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "KN", isoAlpha3: "KNA", nameNl: "Saint Kitts en Nevis", nameEn: "Saint Kitts and Nevis", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "LC", isoAlpha3: "LCA", nameNl: "Saint Lucia", nameEn: "Saint Lucia", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "VC", isoAlpha3: "VCT", nameNl: "Saint Vincent en de Grenadines", nameEn: "Saint Vincent and the Grenadines", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "SR", isoAlpha3: "SUR", nameNl: "Suriname", nameEn: "Suriname", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "TT", isoAlpha3: "TTO", nameNl: "Trinidad en Tobago", nameEn: "Trinidad and Tobago", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "US", isoAlpha3: "USA", nameNl: "Verenigde Staten", nameEn: "United States", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "UY", isoAlpha3: "URY", nameNl: "Uruguay", nameEn: "Uruguay", regionNl: "Amerika", regionEn: "Americas" },
  { isoAlpha2: "VE", isoAlpha3: "VEN", nameNl: "Venezuela", nameEn: "Venezuela", regionNl: "Amerika", regionEn: "Americas" },
  // Oceanië
  { isoAlpha2: "AU", isoAlpha3: "AUS", nameNl: "Australië", nameEn: "Australia", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "FJ", isoAlpha3: "FJI", nameNl: "Fiji", nameEn: "Fiji", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "KI", isoAlpha3: "KIR", nameNl: "Kiribati", nameEn: "Kiribati", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "MH", isoAlpha3: "MHL", nameNl: "Marshalleilanden", nameEn: "Marshall Islands", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "FM", isoAlpha3: "FSM", nameNl: "Micronesië", nameEn: "Micronesia", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "NR", isoAlpha3: "NRU", nameNl: "Nauru", nameEn: "Nauru", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "NZ", isoAlpha3: "NZL", nameNl: "Nieuw-Zeeland", nameEn: "New Zealand", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "PW", isoAlpha3: "PLW", nameNl: "Palau", nameEn: "Palau", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "PG", isoAlpha3: "PNG", nameNl: "Papoea-Nieuw-Guinea", nameEn: "Papua New Guinea", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "WS", isoAlpha3: "WSM", nameNl: "Samoa", nameEn: "Samoa", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "SB", isoAlpha3: "SLB", nameNl: "Salomonseilanden", nameEn: "Solomon Islands", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "TO", isoAlpha3: "TON", nameNl: "Tonga", nameEn: "Tonga", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "TV", isoAlpha3: "TUV", nameNl: "Tuvalu", nameEn: "Tuvalu", regionNl: "Oceanië", regionEn: "Oceania" },
  { isoAlpha2: "VU", isoAlpha3: "VUT", nameNl: "Vanuatu", nameEn: "Vanuatu", regionNl: "Oceanië", regionEn: "Oceania" },
];

// Sample advisory data for demo purposes
const SAMPLE_ADVISORIES = [
  // Thailand
  { sourceId: "uk", destIso2: "TH", rawLevel: "Exercise a high degree of caution", normalizedLevel: "yellow", summary: "Terrorisme en politieke onrust zijn risico's in Thailand. Demonstraties kunnen snel escaleren.", risks: ["terrorisme", "politieke onrust", "demonstraties"], sourceUrl: "https://www.gov.uk/foreign-travel-advice/thailand", officialUpdatedAt: new Date("2026-05-15") },
  { sourceId: "us", destIso2: "TH", rawLevel: "Level 2: Exercise Increased Caution", normalizedLevel: "yellow", summary: "Exercise increased caution due to civil unrest and terrorism concerns.", risks: ["terrorisme", "criminaliteit", "demonstraties"], sourceUrl: "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/thailand-travel-advisory.html", officialUpdatedAt: new Date("2026-04-20") },
  { sourceId: "germany", destIso2: "TH", rawLevel: "Erhöhte Vorsicht", normalizedLevel: "yellow", summary: "Erhöhte Vorsicht wegen politischer Unruhen und Terrorismusrisiken.", risks: ["terrorisme", "politieke onrust"], sourceUrl: "https://www.auswaertiges-amt.de/de/ReiseUndSicherheit/thailand-node", officialUpdatedAt: new Date("2026-05-01") },
  { sourceId: "france", destIso2: "TH", rawLevel: "Vigilance renforcée", normalizedLevel: "yellow", summary: "Vigilance renforcée en raison des risques terroristes et manifestations.", risks: ["terrorisme", "demonstraties"], sourceUrl: "https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays/thailande/", officialUpdatedAt: new Date("2026-03-10") },
  { sourceId: "canada", destIso2: "TH", rawLevel: "Exercise a high degree of caution", normalizedLevel: "yellow", summary: "Exercise a high degree of caution due to ongoing political tensions.", risks: ["politieke onrust", "demonstraties"], sourceUrl: "https://travel.gc.ca/destinations/thailand", officialUpdatedAt: new Date("2026-05-20") },
  { sourceId: "australia", destIso2: "TH", rawLevel: "Exercise a high degree of caution", normalizedLevel: "yellow", summary: "Exercise a high degree of caution. Terrorist attacks could occur.", risks: ["terrorisme", "zakkenrollen"], sourceUrl: "https://www.smartraveller.gov.au/destinations/asia/thailand", officialUpdatedAt: new Date("2026-06-01") },
  { sourceId: "denmark", destIso2: "TH", rawLevel: "Vær forsigtig", normalizedLevel: "yellow", summary: "Vær forsigtig på grund af terrorismerisiko og politisk uro.", risks: ["terrorisme", "politieke onrust"], sourceUrl: "https://um.dk/rejse-og-ophold/rejse-til-udlandet/rejsevejledninger/thailand", officialUpdatedAt: new Date("2026-04-15") },
  { sourceId: "sweden", destIso2: "TH", rawLevel: "Var försiktig", normalizedLevel: "yellow", summary: "Var försiktig med hänsyn till terrorismbrisker och politisk oro.", risks: ["terrorisme", "politieke onrust", "overstromingen"], sourceUrl: "https://www.ud.se/reseinformation/thailand/", officialUpdatedAt: new Date("2026-05-10") },
  // Oekraïne
  { sourceId: "uk", destIso2: "UA", rawLevel: "Advise Against All Travel", normalizedLevel: "red", summary: "Do not travel to Ukraine due to the ongoing armed conflict with Russia.", risks: ["gewapend conflict", "bombardementen", "politieke instabiliteit"], sourceUrl: "https://www.gov.uk/foreign-travel-advice/ukraine", officialUpdatedAt: new Date("2026-06-01") },
  { sourceId: "us", destIso2: "UA", rawLevel: "Level 4: Do Not Travel", normalizedLevel: "red", summary: "Do not travel due to active armed conflict.", risks: ["gewapend conflict", "bombardementen"], sourceUrl: "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/ukraine-travel-advisory.html", officialUpdatedAt: new Date("2026-06-05") },
  { sourceId: "germany", destIso2: "UA", rawLevel: "Reisewarnung", normalizedLevel: "red", summary: "Reisewarnung für die gesamte Ukraine aufgrund des bewaffneten Konflikts.", risks: ["gewapend conflict", "bombardementen"], sourceUrl: "https://www.auswaertiges-amt.de/de/ReiseUndSicherheit/ukraine-node", officialUpdatedAt: new Date("2026-06-03") },
  { sourceId: "france", destIso2: "UA", rawLevel: "Formellement déconseillé", normalizedLevel: "red", summary: "Voyage formellement déconseillé en raison du conflit armé.", risks: ["gewapend conflict"], sourceUrl: "https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays/ukraine/", officialUpdatedAt: new Date("2026-05-28") },
  { sourceId: "canada", destIso2: "UA", rawLevel: "Avoid all travel", normalizedLevel: "red", summary: "Avoid all travel to Ukraine due to the armed conflict.", risks: ["gewapend conflict", "bombardementen"], sourceUrl: "https://travel.gc.ca/destinations/ukraine", officialUpdatedAt: new Date("2026-06-02") },
  { sourceId: "australia", destIso2: "UA", rawLevel: "Do not travel", normalizedLevel: "red", summary: "Do not travel to Ukraine due to the armed conflict and ongoing hostilities.", risks: ["gewapend conflict"], sourceUrl: "https://www.smartraveller.gov.au/destinations/europe/ukraine", officialUpdatedAt: new Date("2026-06-04") },
  { sourceId: "denmark", destIso2: "UA", rawLevel: "Rejse frarådes", normalizedLevel: "red", summary: "Rejse til Ukraine frarådes på grund af den igangværende væbnede konflikt.", risks: ["gewapend conflict"], sourceUrl: "https://um.dk/rejse-og-ophold/rejse-til-udlandet/rejsevejledninger/ukraine", officialUpdatedAt: new Date("2026-06-01") },
  { sourceId: "sweden", destIso2: "UA", rawLevel: "Avråd från resor", normalizedLevel: "red", summary: "Avråd från resor till Ukraina på grund av pågående väpnad konflikt.", risks: ["gewapend conflict", "bombardementen"], sourceUrl: "https://www.ud.se/reseinformation/ukraina/", officialUpdatedAt: new Date("2026-06-02") },
  // Spanje
  { sourceId: "uk", destIso2: "ES", rawLevel: "Exercise a high degree of caution", normalizedLevel: "yellow", summary: "Terrorist attacks in Spain are possible. Be vigilant especially in crowded areas.", risks: ["terrorisme", "zakkenrollen", "betogingen"], sourceUrl: "https://www.gov.uk/foreign-travel-advice/spain", officialUpdatedAt: new Date("2026-05-10") },
  { sourceId: "us", destIso2: "ES", rawLevel: "Level 2: Exercise Increased Caution", normalizedLevel: "yellow", summary: "Exercise increased caution due to terrorism.", risks: ["terrorisme"], sourceUrl: "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/spain-travel-advisory.html", officialUpdatedAt: new Date("2026-04-01") },
  { sourceId: "germany", destIso2: "ES", rawLevel: "Erhöhte Vorsicht", normalizedLevel: "yellow", summary: "Erhöhte Vorsicht wegen Terrorismusgefahr.", risks: ["terrorisme", "zakkenrollen"], sourceUrl: "https://www.auswaertiges-amt.de/de/ReiseUndSicherheit/spanien-node", officialUpdatedAt: new Date("2026-04-15") },
  { sourceId: "france", destIso2: "ES", rawLevel: "Vigilance renforcée", normalizedLevel: "yellow", summary: "Vigilance renforcée en raison du risque terroriste.", risks: ["terrorisme", "zakkenrollen"], sourceUrl: "https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays/espagne/", officialUpdatedAt: new Date("2026-03-20") },
  { sourceId: "canada", destIso2: "ES", rawLevel: "Exercise a high degree of caution", normalizedLevel: "yellow", summary: "Exercise a high degree of caution due to the threat of terrorism.", risks: ["terrorisme"], sourceUrl: "https://travel.gc.ca/destinations/spain", officialUpdatedAt: new Date("2026-05-05") },
  { sourceId: "australia", destIso2: "ES", rawLevel: "Exercise a high degree of caution", normalizedLevel: "yellow", summary: "Exercise a high degree of caution due to terrorism risk.", risks: ["terrorisme", "zakkenrollen"], sourceUrl: "https://www.smartraveller.gov.au/destinations/europe/spain", officialUpdatedAt: new Date("2026-05-20") },
  { sourceId: "denmark", destIso2: "ES", rawLevel: "Vær forsigtig", normalizedLevel: "yellow", summary: "Vær forsigtig på grund af terrorismerisiko.", risks: ["terrorisme"], sourceUrl: "https://um.dk/rejse-og-ophold/rejse-til-udlandet/rejsevejledninger/spanien", officialUpdatedAt: new Date("2026-04-10") },
  { sourceId: "sweden", destIso2: "ES", rawLevel: "Var försiktig", normalizedLevel: "yellow", summary: "Var försiktig med hänsyn till terroristhotet.", risks: ["terrorisme", "zakkenrollen"], sourceUrl: "https://www.ud.se/reseinformation/spanien/", officialUpdatedAt: new Date("2026-04-20") },
  // Marokko
  { sourceId: "uk", destIso2: "MA", rawLevel: "Exercise a high degree of caution", normalizedLevel: "yellow", summary: "Terrorists are likely to try to carry out attacks in Morocco.", risks: ["terrorisme", "zakkenrollen", "oplichting"], sourceUrl: "https://www.gov.uk/foreign-travel-advice/morocco", officialUpdatedAt: new Date("2026-05-01") },
  { sourceId: "us", destIso2: "MA", rawLevel: "Level 2: Exercise Increased Caution", normalizedLevel: "yellow", summary: "Exercise increased caution due to terrorism.", risks: ["terrorisme"], sourceUrl: "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/morocco-travel-advisory.html", officialUpdatedAt: new Date("2026-03-15") },
  { sourceId: "germany", destIso2: "MA", rawLevel: "Erhöhte Vorsicht", normalizedLevel: "yellow", summary: "Erhöhte Vorsicht, besonders in touristischen Gebieten.", risks: ["terrorisme", "zakkenrollen"], sourceUrl: "https://www.auswaertiges-amt.de/de/ReiseUndSicherheit/marokko-node", officialUpdatedAt: new Date("2026-04-05") },
  { sourceId: "france", destIso2: "MA", rawLevel: "Vigilance renforcée", normalizedLevel: "yellow", summary: "Vigilance renforcée en raison du risque terroriste.", risks: ["terrorisme", "demonstraties"], sourceUrl: "https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays/maroc/", officialUpdatedAt: new Date("2026-03-28") },
  { sourceId: "canada", destIso2: "MA", rawLevel: "Exercise a high degree of caution", normalizedLevel: "yellow", summary: "Exercise a high degree of caution due to the threat of terrorism.", risks: ["terrorisme", "zakkenrollen"], sourceUrl: "https://travel.gc.ca/destinations/morocco", officialUpdatedAt: new Date("2026-04-22") },
  { sourceId: "australia", destIso2: "MA", rawLevel: "Exercise a high degree of caution", normalizedLevel: "yellow", summary: "Exercise a high degree of caution. Terrorism is a risk.", risks: ["terrorisme"], sourceUrl: "https://www.smartraveller.gov.au/destinations/africa/morocco", officialUpdatedAt: new Date("2026-05-05") },
  { sourceId: "denmark", destIso2: "MA", rawLevel: "Vær forsigtig", normalizedLevel: "yellow", summary: "Vær forsigtig på grund af terrorismerisiko og kriminalitet.", risks: ["terrorisme", "zakkenrollen"], sourceUrl: "https://um.dk/rejse-og-ophold/rejse-til-udlandet/rejsevejledninger/marokko", officialUpdatedAt: new Date("2026-04-02") },
  { sourceId: "sweden", destIso2: "MA", rawLevel: "Var försiktig", normalizedLevel: "yellow", summary: "Var försiktig med hänsyn till terroristhotet och ficktjuvar.", risks: ["terrorisme", "zakkenrollen"], sourceUrl: "https://www.ud.se/reseinformation/marocko/", officialUpdatedAt: new Date("2026-04-18") },
];

async function main() {
  console.log("Seeding database...");

  // Upsert countries
  for (const country of COUNTRIES) {
    await prisma.country.upsert({
      where: { isoAlpha2: country.isoAlpha2 },
      update: country,
      create: country,
    });
  }
  console.log(`✓ ${COUNTRIES.length} landen ingevoerd`);

  // Upsert sources
  for (const source of SOURCES) {
    await prisma.source.upsert({
      where: { id: source.id },
      update: {
        nameNl: source.nameNl,
        nameEn: source.nameEn,
        countryIso2: source.countryIso2,
        flagEmoji: source.flagEmoji,
        baseUrl: source.baseUrl,
        fetchMethod: source.fetchMethod,
        active: source.active,
        fetchIntervalH: source.fetchIntervalH,
        priority: source.priority,
      },
      create: {
        id: source.id,
        nameNl: source.nameNl,
        nameEn: source.nameEn,
        countryIso2: source.countryIso2,
        flagEmoji: source.flagEmoji,
        baseUrl: source.baseUrl,
        fetchMethod: source.fetchMethod,
        active: source.active,
        fetchIntervalH: source.fetchIntervalH,
        priority: source.priority,
      },
    });
  }
  console.log(`✓ ${SOURCES.length} bronnen ingevoerd`);

  // Upsert sample advisories
  for (const adv of SAMPLE_ADVISORIES) {
    await prisma.advisory.upsert({
      where: { sourceId_destIso2: { sourceId: adv.sourceId, destIso2: adv.destIso2 } },
      update: {
        rawLevel: adv.rawLevel,
        normalizedLevel: adv.normalizedLevel,
        summary: adv.summary,
        risks: JSON.stringify(adv.risks),
        sourceUrl: adv.sourceUrl,
        officialUpdatedAt: adv.officialUpdatedAt,
        scrapedAt: new Date(),
        isStale: false,
      },
      create: {
        sourceId: adv.sourceId,
        destIso2: adv.destIso2,
        rawLevel: adv.rawLevel,
        normalizedLevel: adv.normalizedLevel,
        summary: adv.summary,
        risks: JSON.stringify(adv.risks),
        sourceUrl: adv.sourceUrl,
        officialUpdatedAt: adv.officialUpdatedAt,
        scrapedAt: new Date(),
        isStale: false,
      },
    });
  }
  console.log(`✓ ${SAMPLE_ADVISORIES.length} voorbeeld-adviezen ingevoerd`);

  console.log("Seed voltooid!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
