// Shared fake state for the browser-mode Tauri mock.
// All paths are virtual POSIX-style paths under /mock.

export const MODELS_FOLDER = '/mock/models'
export const DOCUMENTS_FOLDER = '/mock/documents'
export const APP_LOCAL_DATA = '/mock/app-data'
export const DEFAULT_MODEL_FILE = 'ggml-medium.bin'

// Virtual filesystem: path -> contents (string | Uint8Array | null for opaque binaries like models).
export const virtualFs = new Map<string, string | Uint8Array | null>([
	[`${MODELS_FOLDER}/${DEFAULT_MODEL_FILE}`, null],
	[`${DOCUMENTS_FOLDER}/sample.mp3`, null],
	[`${DOCUMENTS_FOLDER}/interview.mp4`, null],
	[`${DOCUMENTS_FOLDER}/meeting-notes.wav`, null],
])

// Pre-saved transcripts so the Recents sidebar has entries to open on first load.
// Shape and filename stamp must match src/lib/transcripts-store.ts.
function seedTranscript(name: string, stamp: string, texts: string[]): [string, string] {
	const record = {
		version: 1,
		name,
		sourcePath: `${DOCUMENTS_FOLDER}/${name}.mp3`,
		createdAt: new Date().toISOString(),
		language: 'english',
		modelPath: `${MODELS_FOLDER}/${DEFAULT_MODEL_FILE}`,
		segments: texts.map((text, index) => ({ start: index * 300, stop: index * 300 + 280, text })),
	}
	return [`${DOCUMENTS_FOLDER}/Vibe/${name}-${stamp}.vibe.json`, JSON.stringify(record)]
}

for (const [path, contents] of [
	seedTranscript('team-standup', '20260820-093015', [
		'Quick recap of what everyone shipped yesterday.',
		'The new release is scheduled for Friday morning.',
		'Open blockers move to the afternoon sync.',
	]),
	seedTranscript('podcast-episode', '20260818-174200', [
		'Welcome back to the show, today we talk about local AI.',
		'On-device transcription keeps your audio private.',
		'Thanks for listening, see you next week.',
	]),
]) {
	virtualFs.set(path, contents)
}

export const sampleSegments: { start: number; stop: number; text: string; speaker?: number }[] = [
	{ start: 0, stop: 240, text: 'Welcome to Vibe running in browser mock mode.' },
	{ start: 240, stop: 520, text: 'This transcript is generated by the mock Tauri layer.' },
	{ start: 520, stop: 800, text: 'Every command and event is simulated in the browser.' },
	{ start: 800, stop: 1100, text: 'Use it to iterate on the UI without the desktop runtime.' },
	{ start: 1100, stop: 1400, text: 'Streaming, progress and errors behave like the real app.' },
]

// Tunables so flows are observable but fast.
export const TRANSCRIBE_SEGMENT_INTERVAL_MS = 700
export const DOWNLOAD_TICKS = 20
export const DOWNLOAD_TICK_MS = 150

export const mockPlatform = 'macos'
export const mockArch = 'aarch64'
export const appVersion = '9.9.9-mock'
export const appName = 'vibe'
