// Shared fake state for the browser-mode Tauri mock.
// All paths are virtual POSIX-style paths under /mock.

export const MODELS_FOLDER = '/mock/models'
export const DOCUMENTS_FOLDER = '/mock/documents'
export const APP_LOCAL_DATA = '/mock/app-data'
export const DEFAULT_MODEL_FILE = 'ggml-medium.bin'

// Virtual filesystem: path -> contents (string | Uint8Array | null for opaque binaries like models).
export const virtualFs = new Map<string, string | Uint8Array | null>([
	[`${MODELS_FOLDER}/${DEFAULT_MODEL_FILE}`, null],
	[`${DOCUMENTS_FOLDER}/sample.mp3`, null],
])

export const sampleSegments: { start: number; stop: number; text: string; speaker?: number }[] = [
	{ start: 0, stop: 240, text: 'Welcome to Vibe running in browser mock mode.' },
	{ start: 240, stop: 520, text: 'This transcript is generated by the mock Tauri layer.' },
	{ start: 520, stop: 800, text: 'Every command and event is simulated in the browser.' },
	{ start: 800, stop: 1100, text: 'Use it to iterate on the UI without the desktop runtime.' },
	{ start: 1100, stop: 1400, text: 'Streaming, progress and errors behave like the real app.' },
]

// Tunables so flows are observable but fast.
export const TRANSCRIBE_SEGMENT_INTERVAL_MS = 700
export const DOWNLOAD_TICKS = 20
export const DOWNLOAD_TICK_MS = 150

export const mockPlatform = 'macos'
export const mockArch = 'aarch64'
export const appVersion = '9.9.9-mock'
export const appName = 'vibe'
